name: CI-CD Helm Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Helm Lint
        run: helm lint ./myapp

      - name: Deploy with Helm
        run: helm upgrade --install myapp ./myapp